---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
- name: create a group devops
  ansible.builtin.group:
    name: devops
    state: present
- name: create a user ainsble devops
  ansible.builtin.user:
    name: devops
    create_home: yes
    group: devops
    home: /opt/tomcat
    shall: /bin/flase
    state: present